#端口
server:
  port: 8082
  servlet:
    context-path: /
#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mtjroot
#mybatis
mybatis:
  type-aliases-package: com.mtjsoft.www.springbootmybatisredis.entity
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:xml/*.xml
